# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself


default_platform(:ios)

platform :ios do
  lane :build_app do
    xcode_select("/Applications/Xcode_15.0.app")
      build_number = Time.new.strftime("%Y%m%d%H%M%S")
      increment_build_number(build_number: build_number,xcodeproj: "Instant-AR.xcodeproj")    

    build_app(
      scheme: "Instant-AR",
      path: "Instant-AR.xcodeproj",
      clean: true,
      export_method: "ad-hoc",
      output_directory: "./Instant-AR"
      output_name: "App.ipa"
    )
    update_project_team(
          path: "Instant-AR.xcodeproj",
          teamid: "M6ENXWGY3Q"
      )
   end
 end
end
