default_platform(:ios)

platform :ios do
desc "Upload build to testflight"
lane :app_store do
    begin
      xcode_select("/Applications/Xcode_15.0.app")
      build_number = Time.new.strftime("%Y%m%d%H%M%S")
      increment_build_number(build_number: build_number,xcodeproj: "Instant-AR.xcodeproj")
      
      update_project_team(
          path: "Instant-AR.xcodeproj",
          teamid: "M6ENXWGY3Q"
      )

      build_app( 
        scheme: "Instant-AR", 
        output_name: "Instant-AR.ipa"
      )

      api_key = app_store_connect_api_key(
                key_id: "6R7ARF43M7",
                issuer_id: "69a6de6f-991b-47e3-e053-5b8c7c11a4d1",
                key_filepath: "./AppstoreAuthKey/AuthKey_6R7ARF43M7.p8",
              )

      pilot(api_key: api_key)
      
      gitMsg    = sh("git log -1 --pretty=%B")
    end
  end
end  
